# build process
FROM nikolaik/python-nodejs:python3.8-nodejs13-alpine AS builder 

# Define workig directory inside the container
RUN mkdir /app
WORKDIR /app

# Install dependencies
COPY ./yarn.lock ./yarn.lock
COPY ./package.json ./package.json
COPY ./tsconfig.json ./tsconfig.json
RUN yarn install

# Coping the application files 
COPY ./public ./public
COPY ./src ./src

# Execute yarn script "start"
CMD [ "yarn", "start" ]

# docker build -f Dockerfile.dev -t 3runo/ker-client-dev .
# docker run -p 3000:3000 --rm -it 3runo/ker-client-dev
# docker exec -it 319bdcabf259 sh 