os: linux
services:
  - docker

before_install:
  - docker build -t 3runo/ker-client-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run 3runo/ker-client-dev yarn test:ci
  - docker run 3runo/ker-client-dev yarn audit:ci

after_success:
  - docker build -t 3runo/ker-route ./nginx
  - docker build -t 3runo/ker-server ./server
  - docker build -t 3runo/ker-client ./client

  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push 3runo/ker-route
  - docker push 3runo/ker-server
  - docker push 3runo/ker-client

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ker"
  env: "Ker-env"
  bucket: "elasticbeanstalk-us-east-2-704958320533"
  bucket_path: "ker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
