os: linux
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t 3runo/ker-client .

script:
  - docker run 3runo/ker-client npm run test:ci
  - docker run 3runo/ker-client npm run audit:ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ker-client-01"
  env: "KerClient01-env"
  bucket: "elasticbeanstalk-us-east-2-704958320533"
  bucket_path: "ker-client-01"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
