sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t 3runo/ker-client .

script:
  - docker run 3runo/ker-client npm run test:ci

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ker-client"
  env: "KerClient-env"
  bucket_name: "elasticbeanstalk-us-east-2-704958320533"
  bucket_path: "ker-client"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
