version: "3"
services:
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - /Users/brunobatista/git/ker/server/index.js:/app/index.js
      - /Users/brunobatista/git/ker/server/src:/app/src
    environment:
      - NODE_ENV=development
      - PORT=4000
      - AWS_DB_REGION=${AWS_DB_REGION}
      - AWS_DB_ACCESS_KEY_ID=${AWS_DB_ACCESS_KEY_ID}
      - AWS_DB_SECRET_ACCESS_KEY=${AWS_DB_SECRET_ACCESS_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  client:
    container_name: client
    depends_on:
      - api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /Users/brunobatista/git/ker/client/public:/app/public
      - /Users/brunobatista/git/ker/client/src:/app/src
      - /Users/brunobatista/git/ker/client/tsconfig.json:/app/tsconfig.json
    environment:
      - NODE_ENV=development

  route:
    container_name: route
    restart: always
    depends_on:
      - api
      - client
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
