version: "3"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    volumes:
      - /c/Users/bruno/git/ker/server/index.js:/app/index.js
      - /c/Users/bruno/git/ker/server/src:/app/src
    environment:
      - NODE_ENV=development
      - PORT=4000
      - AWS_DB_REGION=${AWS_DB_REGION}
      - AWS_DB_ACCESS_KEY_ID=${AWS_DB_ACCESS_KEY_ID}
      - AWS_DB_SECRET_ACCESS_KEY=${AWS_DB_SECRET_ACCESS_KEY}

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /c/Users/bruno/git/ker/client/public:/app/public
      - /c/Users/bruno/git/ker/client/src:/app/src
      - /c/Users/bruno/git/ker/client/tsconfig.json:/app/tsconfig.json
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVER_URI=${REACT_APP_SERVER_URI}
